name: "Pull Request Labeler"
on:
  pull_request:
    types: 
      - opened

jobs:
  community-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - if: ${{ github.event.pull_request.head.repo.fork == 'false' }}
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/workflows/community-pr-labeler.yml"
