name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:   # run once a day at 11.23am (arbitrary but should avoid peak loads on the hour)
    - cron: '23 11 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@3cc123766321e9f15a6676375c154ccffb12a358  # v5.0.0
        with:
          stale-issue-message: 'Message to comment on stale issues.'
          stale-pr-message: 'Message to comment on stale PRs.'
          stale-issue-label: 'needs-info'
          stale-pr-label: 'changes-requested'
          days-before-stale: -1   # Do not apply the stale labels automatically, this is a manual process
          days-before-close: 1   # Close if no updates within this time

